{"name": "test_Logo", "status": "broken", "statusDetails": {"message": "Exception: No such driver version 115.0.5790.114 for mac-x64", "trace": "@pytest.mark.page\n    def test_Logo():\n    \n>       service = Service(executable_path=ChromeDriverManager().install())\n\ntest_page.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../../.conda/envs/automationTest1/lib/python3.10/site-packages/webdriver_manager/chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n../../.conda/envs/automationTest1/lib/python3.10/site-packages/webdriver_manager/core/manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_driver_download_url())\n../../.conda/envs/automationTest1/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py:54: in get_driver_download_url\n    modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <webdriver_manager.drivers.chrome.ChromeDriver object at 0x7fbb88184640>, browser_version = '115.0.5790.114', platform = 'mac-x64'\n\n    def get_url_for_version_and_platform(self, browser_version, platform):\n        url = \"https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json\"\n        response = self._http_client.get(url)\n        data = response.json()\n        versions = data[\"versions\"]\n        for v in versions:\n            if v[\"version\"] == browser_version:\n                downloads = v[\"downloads\"][\"chromedriver\"]\n                for d in downloads:\n                    if d[\"platform\"] == platform:\n                        return d[\"url\"]\n    \n>       raise Exception(f\"No such driver version {browser_version} for {platform}\")\nE       Exception: No such driver version 115.0.5790.114 for mac-x64\n\n../../.conda/envs/automationTest1/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py:89: Exception"}, "start": 1691452472315, "stop": 1691452508164, "uuid": "2a42ce39-19ae-45fd-a00b-88e708607a8d", "historyId": "e20d7015cd52c0d7de8dafb9eae38d71", "testCaseId": "02ba844ab75be68bdb3d3c6301605f9b", "fullName": "test_page#test_Logo", "labels": [{"name": "tag", "value": "page"}, {"name": "suite", "value": "test_page"}, {"name": "host", "value": "test-users-MacBook-Air.local"}, {"name": "thread", "value": "87572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_page"}]}